CREATE OR REPLACE PACKAGE TESTING AS
    PROCEDURE TEST_ITERATIONS(
        ARR IN NUMBER_TABLE.NUMBERTABLE
    );
END TESTING;
/

CREATE OR REPLACE PACKAGE BODY TESTING AS
    PROCEDURE TEST_ITERATIONS(
        ARR IN NUMBER_TABLE.NUMBERTABLE
    ) IS
        LINEAR_SEARCH_ITERATIONS       PLS_INTEGER;
        BINARY_SEARCH_ITERATIONS       PLS_INTEGER;
        LINEAR_SEARCH_TOTAL_ITERATIONS PLS_INTEGER := 0;
        BINARY_SEARCH_TOTAL_ITERATIONS PLS_INTEGER := 0;
    BEGIN
 --Linear search rezultatai po kiekvienos iteracijos
        FOR I IN ARR.FIRST..ARR.LAST LOOP
            LINEAR_SEARCH_ITERATIONS := ALGORYTHMS.LINEARSEARCH(ARR, ARR(I));
            PRINTING.PRINT_SINGLE_ITERATION('linear', ARR(I), LINEAR_SEARCH_ITERATIONS); --SEARCH_TYPE
            LINEAR_SEARCH_TOTAL_ITERATIONS := LINEAR_SEARCH_TOTAL_ITERATIONS + LINEAR_SEARCH_ITERATIONS;
        END LOOP;
 --
 --Binary search rezultatai po kiekvienos iteracijos
        FOR I IN ARR.FIRST..ARR.LAST LOOP
            BINARY_SEARCH_ITERATIONS := ALGORYTHMS.BINARYSEARCH(ARR, ARR(I));
            PRINTING.PRINT_SINGLE_ITERATION('binary', ARR(I), BINARY_SEARCH_ITERATIONS); --SEARCH_TYPE
            BINARY_SEARCH_TOTAL_ITERATIONS := BINARY_SEARCH_TOTAL_ITERATIONS + BINARY_SEARCH_ITERATIONS;
        END LOOP;
 --
 --Atspausdinimui ir kauntui (galima būtų kartu sudėti su forais bet man taip tvarkingiau)
        PRINTING.PRINT_AVERAGE_ITERATIONS('linear', LINEAR_SEARCH_TOTAL_ITERATIONS, ARR.COUNT);
        PRINTING.PRINT_AVERAGE_ITERATIONS('binary', BINARY_SEARCH_TOTAL_ITERATIONS, ARR.COUNT);
    END TEST_ITERATIONS;
END TESTING;
/